### ISSUE TITLE
require("myModule")

### ISSUE THREAD

**Issue by TominoCZ** [mischief/arduino-lua#3]
I've been wondering.. is it possible to use `require("myModule")` and if so, where does it read from?

I have a lua file that looks like this:

```
local module = {};
module.__index = module;

function module.new()
    local self = setmetatable({}, module);

    self._test = math.random(0, 100);

    return self;
end

function module:Print()
    print(self._test);
end

return module;
```

At the moment I load the lua file like so:

```
#define SOL_NO_THREAD_LOCAL 1
#include <Arduino.h>
#include <sol/sol.hpp>

sol::state lua;

extern const char code[] asm("_binary_data_code_lua_start");

void setup() {
    Serial.begin(9600);

    lua.open_libraries(sol::lib::base, sol::lib::table, sol::lib::math, sol::lib::string);
    lua["millis"] = millis;

    auto result = lua.safe_script(code);

    if (!result.valid()) {
        sol::error err = result;
        Serial.println(err.what());
    }
}

void loop() {

}
```

How do I load this code so that I can use it using `require("myModule")`?

**Comment by mischief** [comment]
hi,

i haven't really tried this, so i this is mostly guessing and from memory since i haven't touched any ESP or ESP fs stuff in a while. but i think you would need to change the lua VM's `package.path` to change where require loads from.

you would first need to construct a filesystem. for example, littlefs (or spiffs) for the onboard flash memory. or, you could put files on an sd card if you support that. you also need to initialize the fs in your code.

second you would need to change the package path to point at the VFS path where the fs is registered. for the arduino esp32 package, i believe this is [/littlefs](https://github.com/espressif/arduino-esp32/blob/master/libraries/LittleFS/src/LittleFS.h#L27) or [/sd](https://github.com/espressif/arduino-esp32/blob/master/libraries/SD/src/SD.h#L31) by default. so, i think you could maybe write `package.path = '/littlefs/?.lua'`.

after that you might be able to use require from lua. :grin:

let me know how it goes, and we could maybe add an example to the repo.

**Comment by TominoCZ** [comment]
Does the library try reading from some file system?

Also I just discovered a function that handles the ``require()`` loading but I'm not sure what the function should be returning

This is my code atm, it prints the string I put in `require()`
```
#define SOL_NO_THREAD_LOCAL 1
#include <Arduino.h>
#include <sol/sol.hpp>

sol::state lua;

extern const char myModuleCode[] asm("_binary_data_code_lua_start");
extern const char moduleTesterCode[] asm("_binary_data_test_lua_start");

auto loadModule(const char* name) {
    Serial.println(name);

    // return lua.safe_script(myModuleCode);
}

void setup() {
    Serial.begin(9600);

	lua.open_libraries(sol::lib::base, sol::lib::table, sol::lib::math, sol::lib::string, sol::lib::package);
	lua["millis"] = millis;

    lua.add_package_loader(loadModule);
    //lua["myModule"] = lua.safe_script(code1);

    lua.safe_script(moduleTesterCode);
}

void loop() {

}
```

Returning the loaded script doesn't seem to work and just makes my ESP reboot endlessly.

**Comment by TominoCZ** [comment]
Oh I figured it out!

This line pretty much does it all:
`lua.require_script("myModule", myModuleCode);`

**Comment by mischief** [comment]
> Does the library try reading from some file system?

of course, that is how standard lua works. it uses POSIX fs api calls, which will go through the ESP-IDF sdk vfs hooks.

> 
> Returning the loaded script doesn't seem to work and just makes my ESP reboot endlessly.

i don't have any idea about loading code from an embedded binary in the code like you wrote. i would suggest going for the littlefs/flash file system approach. platformio will automatically create a littlefs for you if you put files in the 'data' directory.. you can follow https://docs.platformio.org/en/stable/platforms/espressif32.html#uploading-files-to-file-system to make a littlefs with files in the data/ directory part of your build.

if you really want `require` to not use FS calls to like load from some arbitrary data or symbol, you probably need to override it and implement it how you want.
